import { all } from 'redux-saga/effects';
import {
  fetchAdminLoginWatcher,
  fetchBookSessionWatcher,
  fetchCoachPaymentWatcher,
  fetchCreatePaymentWatcher,
  fetchEnrollUserWatcher,
  fetchLoginDataWatcher,
  fetchLogoutWatcher,
  fetchReadCoachWatcher,
  fetchReadCourseDetailWatcher,
  fetchReadCourseWatcher,
  fetchReadJobsWatcher,
  fetchReadLessonWatcher,
  fetchReadProfileWatcher,
  fetchReadTemplateWatcher,
  fetchReadTimeSlotWatcher,
  fetchRegisterUserWatcher,
  fetchUserProgressWatcher,
  fetchUpdateProfileWatcher,
  fetchReadExperienceWatcher,
  fetchUpdateExperienceWatcher,
  fetchDeleteExperienceWatcher,
  fetchReadEducationWatcher,
  fetchUpdateEducationWatcher,
  fetchDeleteEducationWatcher,
  fetchReadSkillWatcher,
  fetchStoreSkillWatcher,
  fetchDeleteSkillWatcher,
  fetchReadSkillCategoryWatcher,
  fetchReadProficiencyLevelWatcher,
} from '../watchers/mainWatcher';

export default function* rootSaga() {
  yield all([
    fetchLogoutWatcher(),
    fetchAdminLoginWatcher(),
    fetchLoginDataWatcher(),
    fetchReadCourseWatcher(),
    fetchReadCourseDetailWatcher(),
    fetchRegisterUserWatcher(),
    fetchReadLessonWatcher(),
    fetchEnrollUserWatcher(),
    fetchUserProgressWatcher(),
    fetchCreatePaymentWatcher(),
    fetchReadCoachWatcher(),
    fetchReadTimeSlotWatcher(),
    fetchBookSessionWatcher(),
    fetchReadJobsWatcher(),
    fetchReadTemplateWatcher(),
    fetchReadProfileWatcher(),
    fetchUpdateProfileWatcher(),
    fetchCoachPaymentWatcher(),
    fetchReadExperienceWatcher(),
    fetchUpdateExperienceWatcher(),
    fetchDeleteExperienceWatcher(),
    fetchReadEducationWatcher(),
    fetchUpdateEducationWatcher(),
    fetchDeleteEducationWatcher(),
    fetchReadSkillWatcher(),
    fetchStoreSkillWatcher(),
    fetchDeleteSkillWatcher(),
    fetchReadSkillCategoryWatcher(),
    fetchReadProficiencyLevelWatcher(),
  ]);
}