/* For Auth - Start */
export const INITIATE_FETCH_ADMIN_LOGIN = 'INITIATE_FETCH_ADMIN_LOGIN';
export const SUCCESS_FETCH_ADMIN_LOGIN = 'SUCCESS_FETCH_ADMIN_LOGIN';
export const FAIL_FETCH_ADMIN_LOGIN = 'FAIL_FETCH_ADMIN_LOGIN';
export const CLEAR_ADMIN_LOGIN = 'CLEAR_ADMIN_LOGIN';

export const INITIATE_FETCH_REGISTER_USER = 'INITIATE_FETCH_REGISTER_USER';
export const SUCCESS_FETCH_REGISTER_USER = 'SUCCESS_FETCH_REGISTER_USER';
export const FAIL_FETCH_REGISTER_USER = 'FAIL_FETCH_REGISTER_USER';
export const CLEAR_REGISTER_USER = 'CLEAR_REGISTER_USER';

export const INITIATE_FETCH_LOGOUT = 'INITIATE_FETCH_LOGOUT';
export const SUCCESS_FETCH_LOGOUT = 'SUCCESS_FETCH_LOGOUT';
export const FAIL_FETCH_LOGOUT = 'FAIL_FETCH_LOGOUT';
export const CLEAR_LOGOUT = 'CLEAR_LOGOUT';

export const INITIATE_FETCH_LOGIN_DATA = 'INITIATE_FETCH_LOGIN_DATA';
export const SUCCESS_FETCH_LOGIN_DATA = 'SUCCESS_FETCH_LOGIN_DATA';
export const FAIL_FETCH_LOGIN_DATA = 'FAIL_FETCH_LOGIN_DATA';
export const CLEAR_LOGIN_DATA = 'CLEAR_LOGIN_DATA';
/* For Auth - End */

/* For Course - Start */
export const INITIATE_FETCH_READ_COURSES = 'INITIATE_FETCH_READ_COURSES';
export const SUCCESS_FETCH_READ_COURSES = 'SUCCESS_FETCH_READ_COURSES';
export const FAIL_FETCH_READ_COURSES = 'FAIL_FETCH_READ_COURSES';
export const CLEAR_READ_COURSES = 'CLEAR_READ_COURSES';

export const INITIATE_FETCH_READ_COURSE_DETAIL = 'INITIATE_FETCH_READ_COURSE_DETAIL';
export const SUCCESS_FETCH_READ_COURSE_DETAIL = 'SUCCESS_FETCH_READ_COURSE_DETAIL';
export const FAIL_FETCH_READ_COURSE_DETAIL = 'FAIL_FETCH_READ_COURSE_DETAIL';
export const CLEAR_READ_COURSE_DETAIL = 'FAIL_FETCH_READ_COURSE_DETAIL';

export const INITIATE_FETCH_LESSONS = 'INITIATE_FETCH_LESSONS';
export const SUCCESS_FETCH_LESSONS = 'SUCCESS_FETCH_LESSONS';
export const FAIL_FETCH_LESSONS = 'FAIL_FETCH_LESSONS';
export const CLEAR_LESSONS = 'CLEAR_LESSONS';

export const INITIATE_FETCH_ENROLL_USER = 'INITIATE_FETCH_ENROLL_USER';
export const SUCCESS_FETCH_ENROLL_USER = 'SUCCESS_FETCH_ENROLL_USER';
export const FAIL_FETCH_ENROLL_USER = 'FAIL_FETCH_ENROLL_USER';
export const CLEAR_ENROLL_USER = 'CLEAR_ENROLL_USER';

export const INITIATE_FETCH_USER_PROGRESS = 'INITIATE_FETCH_USER_PROGRESS';
export const SUCCESS_FETCH_USER_PROGRESS = 'SUCCESS_FETCH_USER_PROGRESS';
export const FAIL_FETCH_USER_PROGRESS = 'FAIL_FETCH_USER_PROGRESS';
export const CLEAR_USER_PROGRESS = 'CLEAR_USER_PROGRESS';

export const INITIATE_FETCH_CREATE_PAYMENT = 'INITIATE_FETCH_CREATE_PAYMENT';
export const SUCCESS_FETCH_CREATE_PAYMENT = 'SUCCESS_FETCH_CREATE_PAYMENT';
export const FAIL_FETCH_CREATE_PAYMENT = 'FAIL_FETCH_CREATE_PAYMENT';
export const CLEAR_CREATE_PAYMENT = 'CLEAR_CREATE_PAYMENT';
/* For Course - End */

/* For Coaching - Start */
export const INITIATE_FETCH_READ_COACHES = 'INITIATE_FETCH_READ_COACHES';
export const SUCCESS_FETCH_READ_COACHES = 'SUCCESS_FETCH_READ_COACHES';
export const FAIL_FETCH_READ_COACHES = 'FAIL_FETCH_READ_COACHES';
export const CLEAR_READ_COACHES = 'CLEAR_READ_COACHES';

export const INITIATE_FETCH_READ_TIMESLOTS = 'INITIATE_FETCH_READ_TIMESLOTS';
export const SUCCESS_FETCH_READ_TIMESLOTS = 'SUCCESS_FETCH_READ_TIMESLOTS';
export const FAIL_FETCH_READ_TIMESLOTS = 'FAIL_FETCH_READ_TIMESLOTS';
export const CLEAR_READ_TIMESLOTS = 'CLEAR_READ_TIMESLOTS';

export const INITIATE_FETCH_BOOK_COACH = 'INITIATE_FETCH_BOOK_COACH';
export const SUCCESS_FETCH_BOOK_COACH = 'SUCCESS_FETCH_BOOK_COACH';
export const FAIL_FETCH_BOOK_COACH = 'FAIL_FETCH_BOOK_COACH';
export const CLEAR_BOOK_COACH = 'CLEAR_BOOK_COACH';

/* For Coaching Payment - Start */
export const INITIATE_FETCH_COACH_PAYMENT = 'INITIATE_FETCH_COACH_PAYMENT';
export const SUCCESS_FETCH_COACH_PAYMENT = 'SUCCESS_FETCH_COACH_PAYMENT';
export const FAIL_FETCH_COACH_PAYMENT = 'FAIL_FETCH_COACH_PAYMENT';
export const CLEAR_COACH_PAYMENT = 'CLEAR_COACH_PAYMENT';
/* For Coaching Payment - End */

/* For Coaching - End */

/* For Jobs - Start */
export const INITIATE_FETCH_READ_JOBS = 'INITIATE_FETCH_READ_JOBS';
export const SUCCESS_FETCH_READ_JOBS = 'SUCCESS_FETCH_READ_JOBS';
export const FAIL_FETCH_READ_JOBS = 'FAIL_FETCH_READ_JOBS';
export const CLEAR_READ_JOBS = 'CLEAR_READ_JOBS';
/* For Job - End */

/* For Profile - Start */
export const INITIATE_FETCH_READ_PROFILE = 'INITIATE_FETCH_READ_PROFILE';
export const SUCCESS_FETCH_READ_PROFILE = 'SUCCESS_FETCH_READ_PROFILE';
export const FAIL_FETCH_READ_PROFILE = 'FAIL_FETCH_READ_PROFILE';
export const CLEAR_READ_PROFILE = 'CLEAR_READ_PROFILE';

export const INITIATE_UPDATE_PROFILE = 'INITIATE_UPDATE_PROFILE';
export const SUCCESS_UPDATE_PROFILE = 'SUCCESS_UPDATE_PROFILE';
export const FAIL_UPDATE_PROFILE = 'FAIL_UPDATE_PROFILE';
export const CLEAR_UPDATE_PROFILE = 'CLEAR_UPDATE_PROFILE';
/* For Profile - End */

/* For CV Builder - Start */
export const INITIATE_FETCH_READ_TEMPLATES = 'INITIATE_FETCH_READ_TEMPLATES';
export const SUCCESS_FETCH_READ_TEMPLATES = 'SUCCESS_FETCH_READ_TEMPLATES';
export const FAIL_FETCH_READ_TEMPLATES = 'FAIL_FETCH_READ_TEMPLATES';
export const CLEAR_READ_TEMPLATES = 'CLEAR_READ_TEMPLATES';
/* For CV Builder - End */

/* For Experiences - Start */
export const INITIATE_FETCH_READ_EXPERIENCES = 'INITIATE_FETCH_READ_EXPERIENCES';
export const SUCCESS_FETCH_READ_EXPERIENCES = 'SUCCESS_FETCH_READ_EXPERIENCES';
export const FAIL_FETCH_READ_EXPERIENCES = 'FAIL_FETCH_READ_EXPERIENCES';
export const CLEAR_READ_EXPERIENCES = 'CLEAR_READ_EXPERIENCES';

/* For Experiences - Update */
export const INITIATE_UPDATE_EXPERIENCES = 'INITIATE_UPDATE_EXPERIENCES';
export const SUCCESS_UPDATE_EXPERIENCES = 'SUCCESS_UPDATE_EXPERIENCES';
export const FAIL_UPDATE_EXPERIENCES = 'FAIL_UPDATE_EXPERIENCES';
export const CLEAR_UPDATE_EXPERIENCES = 'CLEAR_UPDATE_EXPERIENCES';

/* For Experiences - Delete */
export const INITIATE_DELETE_EXPERIENCES = 'INITIATE_DELETE_EXPERIENCES';
export const SUCCESS_DELETE_EXPERIENCES = 'SUCCESS_DELETE_EXPERIENCES';
export const FAIL_DELETE_EXPERIENCES = 'FAIL_DELETE_EXPERIENCES';
export const CLEAR_DELETE_EXPERIENCES = 'CLEAR_DELETE_EXPERIENCES';
/* For Experiences - End */

/* For Educations - Start */
export const INITIATE_FETCH_READ_EDUCATIONS = 'INITIATE_FETCH_READ_EDUCATIONS';
export const SUCCESS_FETCH_READ_EDUCATIONS = 'SUCCESS_FETCH_READ_EDUCATIONS';
export const FAIL_FETCH_READ_EDUCATIONS = 'FAIL_FETCH_READ_EDUCATIONS';
export const CLEAR_READ_EDUCATIONS = 'CLEAR_READ_EDUCATIONS';
/* For Educations - End */

/* For Educations - Update */
export const INITIATE_UPDATE_EDUCATIONS = 'INITIATE_UPDATE_EDUCATIONS';
export const SUCCESS_UPDATE_EDUCATIONS = 'SUCCESS_UPDATE_EDUCATIONS';
export const FAIL_UPDATE_EDUCATIONS = 'FAIL_UPDATE_EDUCATIONS';
export const CLEAR_UPDATE_EDUCATIONS = 'CLEAR_UPDATE_EDUCATIONS';
/* For Educations - End */

/* For Educations - Delete */
export const INITIATE_DELETE_EDUCATIONS = 'INITIATE_DELETE_EDUCATIONS';
export const SUCCESS_DELETE_EDUCATIONS = 'SUCCESS_DELETE_EDUCATIONS';
export const FAIL_DELETE_EDUCATIONS = 'FAIL_DELETE_EDUCATIONS';
export const CLEAR_DELETE_EDUCATIONS = 'CLEAR_DELETE_EDUCATIONS';
/* For Educations - End */

/* For Skills - Read */
export const INITIATE_FETCH_READ_SKILLS = 'INITIATE_FETCH_READ_SKILLS';
export const SUCCESS_FETCH_READ_SKILLS = 'SUCCESS_FETCH_READ_SKILLS';
export const FAIL_FETCH_READ_SKILLS = 'FAIL_FETCH_READ_SKILLS';
export const CLEAR_READ_SKILLS = 'CLEAR_READ_SKILLS';

/* For Skills - Store */
export const INITIATE_STORE_SKILLS = 'INITIATE_STORE_SKILLS';
export const SUCCESS_STORE_SKILLS = 'SUCCESS_STORE_SKILLS';
export const FAIL_STORE_SKILLS = 'FAIL_STORE_SKILLS';
export const CLEAR_STORE_SKILLS = 'CLEAR_STORE_SKILLS';

/* For Skills - Delete */
export const INITIATE_DELETE_SKILLS = 'INITIATE_DELETE_SKILLS';
export const SUCCESS_DELETE_SKILLS = 'SUCCESS_DELETE_SKILLS';
export const FAIL_DELETE_SKILLS = 'FAIL_DELETE_SKILLS';
export const CLEAR_DELETE_SKILLS = 'CLEAR_DELETE_SKILLS';

/* For Skill Categories - Read */
export const INITIATE_FETCH_READ_SKILL_CATEGORIES = 'INITIATE_FETCH_READ_SKILL_CATEGORIES';
export const SUCCESS_FETCH_READ_SKILL_CATEGORIES = 'SUCCESS_FETCH_READ_SKILL_CATEGORIES';
export const FAIL_FETCH_READ_SKILL_CATEGORIES = 'FAIL_FETCH_READ_SKILL_CATEGORIES';
export const CLEAR_READ_SKILL_CATEGORIES = 'CLEAR_READ_SKILL_CATEGORIES';
/* For Proficiency Levels - Read */
export const INITIATE_FETCH_READ_PROFICIENCY_LEVELS = 'INITIATE_FETCH_READ_PROFICIENCY_LEVELS';
export const SUCCESS_FETCH_READ_PROFICIENCY_LEVELS = 'SUCCESS_FETCH_READ_PROFICIENCY_LEVELS';
export const FAIL_FETCH_READ_PROFICIENCY_LEVELS = 'FAIL_FETCH_READ_PROFICIENCY_LEVELS';
export const CLEAR_READ_PROFICIENCY_LEVELS = 'CLEAR_READ_PROFICIENCY_LEVELS';
/* For Skills - End */